import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Box from "@mui/material/Stack";
import "leaflet/dist/leaflet.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CircleLens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box
          sx={{
            height: "100vh",
            minHeight: "100vh",
            width: "100vw",
            minWidth: "100vw",
            "@supports (height: 100dvh)": {
              height: "100dvh",
              minHeight: "100dvh",
            },
            "@supports (height: 100dvw)": {
              width: "100dvw",
              minWidth: "100dvw",
            },
          }}
        >
          {children}
        </Box>
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";
export const revalidate = 0;
